# Define UI for app that draws a histogram ----
library(shiny)
library(divwheel)
if (!require("markdown"))
  install.packages("markdown")
library(markdown)
if (!require("shinydashboard"))
  install.packages("shinydashboard")
library(shinydashboard)
if (!require("shinyWidgets"))
  install.packages("shinyWidgets")
if (!require("plotly"))
  install.packages("plotly")
library(plotly)
if (!require("stringi"))
  install.packages('stringi')
library('stringi')
# install.packages("RPostgreSQL")
if (!require("RPostgres"))
  install.packages("RPostgres")
library(RPostgres)
if (!require("dotenv"))
  install.packages("dotenv")
library(dotenv)
library(DBI)
if (!require("dplyr"))
  install.packages("dplyr")
library(dplyr)
if (!require("rlist"))
  install.packages("rlist")
library("rlist")
if (!require("stringr"))
  install.packages("stringr")
library(stringr)
if (!require("shinyjs"))
  install.packages("shinyjs")
library(shinyjs)

sourceDir <- getSrcDirectory(function(dummy) {dummy})
load_dot_env()

source("data.R")
source("helper.R")
source("data_connect.R")


