install.packages("htmlwidgets")
install.packages("devtools")
library("htmlwidgets")
library("devtools")
# create package using devtools
#devtools::create("divwheel")  
#setwd("divwheel")  
#scaffoldWidget("divwheelnav", edit = FALSE)
#install()

#library(divwheel)
#divwheelnav("hello, world")
devtools::install("./divwheel")
library(divwheel)
divwheelnav(c(1,0,0,0,1,1,1,1), c("ODD1","ODD1","ODD1","ODD1","ODD1","ODD1","ODD1","ODD1"))
